# Generated by Django 3.2.13 on 2023-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('ISBN', models.CharField(max_length=20)),
            ],
        ),
    ]
